config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins

  resources :invoice_items

  resources :invoices

  resources :users

  resources :clients

  root 'welcome#home'

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  scope :for_month, ->(time) { where("created_at >= ? AND ? < created_at", time.beginning_of_month, time.end_of_month) } 
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params[:invoice]
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.slim
= form_for @invoice do |f|
  - if @invoice.errors.any?
    #error_explanation
      h2 = "#{pluralize(@invoice.errors.count, "error")} prohibited this invoice from being saved:"
      ul
        - @invoice.errors.full_messages.each do |message|
          li = message

  .actions = f.submit 'Save'

app/views/invoices/edit.html.slim
h1 Editing invoice

== render 'form'

= link_to 'Show', @invoice
'|
= link_to 'Back', invoices_path

app/views/invoices/index.html.slim
h1 Listing invoices

table
  thead
    tr
      th
      th
      th

  tbody
    - @invoices.each do |invoice|
      tr
        td = link_to 'Show', invoice
        td = link_to 'Edit', edit_invoice_path(invoice)
        td = link_to 'Destroy', invoice, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Invoice', new_invoice_path

app/views/invoices/new.html.slim
h1 New invoice

== render 'form'

= link_to 'Back', invoices_path

app/views/invoices/show.html.slim
p#notice = notice


= link_to 'Edit', edit_invoice_path(@invoice)
'|
= link_to 'Back', invoices_path