config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins

  resources :invoice_items

  resources :invoices

  resources :users

  resources :clients

  root 'welcome#home'

end

app/models/client.rb
class Client < ActiveRecord::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params[:client]
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.slim
= form_for @client do |f|
  - if @client.errors.any?
    #error_explanation
      h2 = "#{pluralize(@client.errors.count, "error")} prohibited this client from being saved:"
      ul
        - @client.errors.full_messages.each do |message|
          li = message

  .actions = f.submit 'Save'

app/views/clients/edit.html.slim
h1 Editing client

== render 'form'

= link_to 'Show', @client
'|
= link_to 'Back', clients_path

app/views/clients/index.html.slim
h1 Listing clients

table
  thead
    tr
      th
      th
      th

  tbody
    - @clients.each do |client|
      tr
        td = link_to 'Show', client
        td = link_to 'Edit', edit_client_path(client)
        td = link_to 'Destroy', client, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Client', new_client_path

app/views/clients/new.html.slim
h1 New client

== render 'form'

= link_to 'Back', clients_path

app/views/clients/show.html.slim
p#notice = notice


= link_to 'Edit', edit_client_path(@client)
'|
= link_to 'Back', clients_path