config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins

  resources :invoice_items

  resources :invoices

  resources :users

  resources :clients

  root 'welcome#home'

end

app/models/invoice_item.rb
class InvoiceItem < ActiveRecord::Base
end

app/controllers/invoice_items_controller.rb
class InvoiceItemsController < ApplicationController
  before_action :set_invoice_item, only: [:show, :edit, :update, :destroy]

  # GET /invoice_items
  # GET /invoice_items.json
  def index
    @invoice_items = InvoiceItem.all
  end

  # GET /invoice_items/1
  # GET /invoice_items/1.json
  def show
  end

  # GET /invoice_items/new
  def new
    @invoice_item = InvoiceItem.new
  end

  # GET /invoice_items/1/edit
  def edit
  end

  # POST /invoice_items
  # POST /invoice_items.json
  def create
    @invoice_item = InvoiceItem.new(invoice_item_params)

    respond_to do |format|
      if @invoice_item.save
        format.html { redirect_to @invoice_item, notice: 'Invoice item was successfully created.' }
        format.json { render :show, status: :created, location: @invoice_item }
      else
        format.html { render :new }
        format.json { render json: @invoice_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoice_items/1
  # PATCH/PUT /invoice_items/1.json
  def update
    respond_to do |format|
      if @invoice_item.update(invoice_item_params)
        format.html { redirect_to @invoice_item, notice: 'Invoice item was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice_item }
      else
        format.html { render :edit }
        format.json { render json: @invoice_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoice_items/1
  # DELETE /invoice_items/1.json
  def destroy
    @invoice_item.destroy
    respond_to do |format|
      format.html { redirect_to invoice_items_url, notice: 'Invoice item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice_item
      @invoice_item = InvoiceItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_item_params
      params[:invoice_item]
    end
end

app/helpers/invoice_items_helper.rb
module InvoiceItemsHelper
end

app/views/invoice_items/_form.html.slim
= form_for @invoice_item do |f|
  - if @invoice_item.errors.any?
    #error_explanation
      h2 = "#{pluralize(@invoice_item.errors.count, "error")} prohibited this invoice_item from being saved:"
      ul
        - @invoice_item.errors.full_messages.each do |message|
          li = message

  .actions = f.submit 'Save'

app/views/invoice_items/edit.html.slim
h1 Editing invoice_item

== render 'form'

= link_to 'Show', @invoice_item
'|
= link_to 'Back', invoice_items_path

app/views/invoice_items/index.html.slim
h1 Listing invoice_items

table
  thead
    tr
      th
      th
      th

  tbody
    - @invoice_items.each do |invoice_item|
      tr
        td = link_to 'Show', invoice_item
        td = link_to 'Edit', edit_invoice_item_path(invoice_item)
        td = link_to 'Destroy', invoice_item, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Invoice item', new_invoice_item_path

app/views/invoice_items/new.html.slim
h1 New invoice_item

== render 'form'

= link_to 'Back', invoice_items_path

app/views/invoice_items/show.html.slim
p#notice = notice


= link_to 'Edit', edit_invoice_item_path(@invoice_item)
'|
= link_to 'Back', invoice_items_path